# Generated by Django 2.2.2 on 2019-06-28 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0003_questions_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotesAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_vote', models.BooleanField(default=False)),
                ('down_vote', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VotesQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_vote', models.BooleanField(default=False)),
                ('down_vote', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='up_votes',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='votesquestion',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Questions'),
        ),
        migrations.AddField(
            model_name='votesquestion',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votesanswers',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Questions'),
        ),
        migrations.AddField(
            model_name='votesanswers',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
