# Generated by Django 2.2.2 on 2019-06-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_auto_20190630_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votesanswers',
            name='qid',
        ),
        migrations.RemoveField(
            model_name='votesanswers',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='votesquestion',
            name='qid',
        ),
        migrations.RemoveField(
            model_name='votesquestion',
            name='uid',
        ),
        migrations.DeleteModel(
            name='QueTag',
        ),
        migrations.DeleteModel(
            name='VotesAnswers',
        ),
        migrations.DeleteModel(
            name='VotesQuestion',
        ),
    ]
